### ISSUE TITLE
RtmInvalidStatusError:  Error Code 5 - The channel does not join. Cannot do the operation.

### ISSUE THREAD

**Issue by jojonarte** [AgoraIO-Community/Agora-RTM-React#3]
I'm getting below error
```
Uncaught (in promise) RtmInvalidStatusError:  Error Code 5 - The channel does not join. Cannot do the operation.
```

when trying to send message via 

```
const sendMessage = async () => {
  const bytes = new Uint8Array([97, 100, 100, 83, 116, 114, 111, 107, 101, 80, 111, 105, 110, 116, 115, 58, 0, 4, 61, 7, -57, 126, -67, -11, -52, 99, -66, -8, 123, 33, 0, 4, 61, 8, -102, -108, -67, -37, -59, -91, -66, -7, -3, 108, 0, 4, 61, 3, -69, 20, -67, -59, -126, -67, -66, -5, 47, -62, 0, 4, 60, -7, 12, 19, -67, -81, 124, -67, -66, -4, 66, -20])
        await rtmChannel?.sendMessage({ rawMessage: bytes })
}

```

**Comment by EkaanshArora** [comment]
I think you haven't joined a channel successfully and are trying to send a message

**Comment by jojonarte** [comment]
> I think you haven't joined a channel successfully and are trying to send a message

Before the `sendMessage` was triggered I could confirm that the joining into channel resolved through this
```
await rtmChannel.join().then(() => console.log('@@@JOINED'))
```
Is there a specific way to know that joining the channel was successful?

**Comment by EkaanshArora** [comment]
you can listen to the channel join success event

**Comment by jojonarte** [comment]
@EkaanshArora do you mean the `MemberJoined`? It's never called. What are possible issues?

**Comment by jojonarte** [comment]
@EkaanshArora I can confirm now that MemberJoined was called, however the message is still not being sent successfully with the same error.
