### ISSUE TITLE
sendMessage failed with args: {"rawMessage":"[Hidden Info]","messageType":"RAW"}. +0ms

### ISSUE THREAD

**Issue by jojonarte** [AgoraIO-Community/Agora-RTM-React#5]
How to debug this kind of error? I had this when trying to send raw UInt8Array `rawMessage` to `rtmChannel.sendMessage.`

**Comment by EkaanshArora** [comment]
This looks like an RTM issue - usually happens when channel/user isn’t joined and you try to send message.  
Can you open a support ticket at https://agora-ticket.agora.io/
