### ISSUE TITLE
createClient() not working with environment variables

### ISSUE THREAD

**Issue by BMTCompany2** [AgoraIO-Community/Agora-RTM-React#7]
createClient() won't accept an environment variable.  

I'm trying to use environment variables inside createClient() like this:

`const useRtmClient = createClient(`${agoraAppId}`);`

But I get this error when I do: RtmInvalidArgumentError:  Error Code 1 - The appId in the arguments is invalid

If instead I do 

``const useRtmClient = createClient('#####');``

There is no error.

**Comment by EkaanshArora** [comment]
Seems like an issue with your env config, I'd suggest trying to log the value and see if it's accessible. This isn't a problem with this library.

**Comment by BMTCompany2** [comment]
Yes thanks, I forgot to prefix the env variables with REAC_APP.
